name: Build and Push Docker Image
on:
  push:
    branches:
      - develop

jobs:
  build-and-push-image:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: |
            zarathucorp/indulgentia-front

      - name: Set TAG env
        run: echo "RELEASE_VERSION=v$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Metadata
        run: echo "container tag will be 'latest' and '${{ env.RELEASE_VERSION }}'"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Set env before build
        run: |
          touch .env.local
          echo "NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}" >> .env.local
          echo "NEXT_PUBLIC_FRONTEND_URL=${{ secrets.NEXT_PUBLIC_FRONTEND_URL }}" >> .env.local
          echo "NEXT_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}" >> .env.local
          echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}" >> .env.local
          echo "AZURE_STORAGE_CONNECTION_STRING=${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}" >> .env.local
          echo "DEFAULT_AZURE_CONTAINER_NAME=${{ secrets.DEFAULT_AZURE_CONTAINER_NAME }}" >> .env.local

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/indulgentia-front:latest
            ghcr.io/${{ github.repository_owner }}/indulgentia-front:${{ env.RELEASE_VERSION }}
            
      - name: Trigger rndsillog-network repo action
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GHCR_TOKEN }}" \
          -d '{"event_type": "trigger"}' \
          https://api.github.com/repos/zarathucorp/rndsillog-network/dispatches